/** Device detection utilities for mobile mode and device-specific optimization. */

/** Returns true if the device is likely a phone or tablet with touch input. */
export function detectMobileLike(): boolean {
  // Primary: coarse pointer means finger/stylus as the main input — most reliable
  if (window.matchMedia?.('(pointer: coarse)')?.matches) return true;
  // Small screen + touch support (catches tablets in landscape, etc.)
  // maxTouchPoints alone false-positives on many Windows desktops
  if (navigator.maxTouchPoints > 0 && Math.min(screen.width, screen.height) < 768) return true;
  return false;
}

/** Returns true if the device is running iOS (iPhone, iPad, iPod).
 *  Handles iPad masquerading as Mac in Safari 13+. */
export function isiOS(): boolean {
  if (/iPad|iPhone|iPod/.test(navigator.userAgent)) return true;
  // iPad on iOS 13+ reports as Mac but has touch
  if (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1) return true;
  return false;
}

/** Returns true if the active device profile is a phone tier (not tablet/desktop). */
export function isPhoneTier(tier: string): boolean {
  return tier === 'phone-high' || tier === 'gen-mobile' || tier === 'phone-low';
}

/** Auto-compute musicUIScale for unknown devices based on screen dimensions.
 *  Smaller screens get higher scale so the popup content is readable. */
function autoMusicUIScale(): number {
  const shortest = Math.min(screen.width, screen.height);
  // ~360px (iPhone Mini) → 1.5, ~414px (iPhone Plus) → 1.3, ~430px → 1.26
  return Math.max(1.0, Math.min(2.0, 540 / shortest));
}

// ── Device Profiles ─────────────────────────────────────────────

export type DeviceTier = 'desktop' | 'tablet' | 'phone-high' | 'gen-mobile' | 'phone-low';

/** Sprite resolution tier — selects which pre-scaled spritesheet variant to load.
 *  s100 = full res (desktop), s75 = 75%, s50 = existing _mobile, s37 = 37.5%, s25 = 25%.
 *  Generated by: node scripts/gen-sprite-tiers.mjs */
export type SpriteTier = 's100' | 's75' | 's50' | 's37' | 's25';

export interface DeviceProfile {
  tier: DeviceTier;
  label: string;              // Human-readable name shown in debug
  crt: boolean;               // Enable CRT post-processing pipeline
  reflections: boolean;       // Enable puddle reflection system
  carCount: number;           // Oncoming traffic count (0 = disabled)
  parallaxLayers: number;     // Number of parallax background layers
  maxParallelLoads: number;   // Loader concurrency
  musicUIScale: number;       // Music player popup scale on phones (1.0 = no extra scaling)
  titleAnimLevel: number | null; // Title animation resolution level (0=full, 25=half, null=static)
  renderScale: number;        // Internal render resolution multiplier (1.0=1920x1080, 0.5=960x540)
  reflectionRTScale: number;  // Reflection RenderTexture resolution (0.5=960×540, 0.25=480×270)
  reflectionTexScale: number; // Parallax reflection texture downscale (0.2=20%, 0.1=10%)
  reflectionSkip: number;     // RT redraw interval (1=every frame, 2=half, 3=third, 4=quarter)
  liteMode: boolean;          // Skip heavy animation spritesheets (~88MB VRAM savings)
  spriteTier: SpriteTier;     // Which resolution tier for player animation spritesheets
}

/** Default profiles per tier. Exported so DeviceSimulator can reuse instead of duplicating. */
export const TIER_DEFAULTS: Record<DeviceTier, DeviceProfile> = {
  'desktop': {
    tier: 'desktop',
    label: 'Desktop',
    crt: true,
    reflections: true,
    carCount: 5,
    parallaxLayers: 8,
    maxParallelLoads: 32,
    musicUIScale: 1.0,
    titleAnimLevel: 0,    // full-res originals
    renderScale: 1.0,
    reflectionRTScale: 0.5,
    reflectionTexScale: 0.2,
    reflectionSkip: 1,
    liteMode: false,
    spriteTier: 's100',   // full-res spritesheets (376 MB VRAM)
  },
  'tablet': {
    tier: 'tablet',
    label: 'Tablet (iPad)',
    crt: true,
    reflections: true,
    carCount: 5,
    parallaxLayers: 8,
    maxParallelLoads: 4,
    musicUIScale: 1.0,
    titleAnimLevel: 0,    // full-res originals
    renderScale: 1.0,
    reflectionRTScale: 0.5,
    reflectionTexScale: 0.2,
    reflectionSkip: 1,
    liteMode: false,
    spriteTier: 's75',    // 75% spritesheets (211 MB VRAM) — iPads have 4-6GB
  },
  'phone-high': {
    tier: 'phone-high',
    label: 'Phone High (A14+)',
    crt: true,
    reflections: true,
    carCount: 2,
    parallaxLayers: 6,
    maxParallelLoads: 2,
    musicUIScale: 1.4,
    titleAnimLevel: 25,   // 960x540 — tested smooth on 12 Mini with CRT
    renderScale: 0.75,    // 1440x810 — A14+ can handle 75%
    reflectionRTScale: 0.5,
    reflectionTexScale: 0.2,
    reflectionSkip: 2,
    liteMode: false,      // Proven capable — 12 Mini stable at 35 FPS
    spriteTier: 's50',    // 50% spritesheets (94 MB VRAM) — 4GB phones
  },
  'gen-mobile': {
    tier: 'gen-mobile',
    label: 'GEN Mobile (unknown)',
    crt: true,
    reflections: true,    // ON — quality scaled via reflectionRTScale/Skip
    carCount: 2,
    parallaxLayers: 6,
    maxParallelLoads: 2,
    musicUIScale: 1.3,
    titleAnimLevel: 35,   // 576x324 — conservative for unknowns
    renderScale: 0.5,     // 960x540 — safe default for unknowns
    reflectionRTScale: 0.35,
    reflectionTexScale: 0.15,
    reflectionSkip: 3,
    liteMode: true,       // Unknown device = play it safe
    spriteTier: 's37',    // 37.5% spritesheets (53 MB VRAM) — safe for unknowns
  },
  'phone-low': {
    tier: 'phone-low',
    label: 'Phone Low (A12/A13)',
    crt: true,
    reflections: true,    // ON — quality scaled via reflectionRTScale/Skip
    carCount: 1,          // Bring back 1 car (was 0) — tiny 20% sprites
    parallaxLayers: 8,
    maxParallelLoads: 2,
    musicUIScale: 1.2,
    titleAnimLevel: 35,  // 576x324 — tested 31 FPS on 12 Mini (no CRT)
    renderScale: 0.5,    // 960x540 — 4x fewer pixels, targeting 30+ FPS
    reflectionRTScale: 0.5,   // Same as desktop — start safe, reduce after testing
    reflectionTexScale: 0.2,  // Same as desktop — start safe, reduce after testing
    reflectionSkip: 3,        // Redraw every 3rd frame
    liteMode: true,           // Lowest tier = always lite
    spriteTier: 's37',   // 37.5% spritesheets (53 MB VRAM) — animated > static
  },
};

/** Device registry entry — testing-driven tier assignment with per-device overrides.
 *  Every phone starts at phone-low (safest). Only TESTED devices get promoted.
 *  Overrides fine-tune parameters within a tier without changing the tier itself. */
export interface DeviceRegistryEntry {
  w: number;              // screen.width (CSS px, portrait)
  h: number;              // screen.height (CSS px, portrait)
  dpr: number;
  label: string;          // Human-readable name
  currentTier: DeviceTier;  // Where this device sits NOW (testing-driven)
  overrides: Partial<Omit<DeviceProfile, 'tier' | 'label'>>;  // Per-device fine-tuning
  testStatus?: string;    // Testing notes (e.g. "tested-2026-02-26: 35fps, 0 crashes")
}

/** Build a complete DeviceProfile by merging tier defaults with device-specific overrides. */
export function buildProfile(entry: DeviceRegistryEntry): DeviceProfile {
  return {
    ...TIER_DEFAULTS[entry.currentTier],
    ...entry.overrides,
    tier: entry.currentTier,
    label: entry.label,
  };
}

/** Device registry — iOS fingerprints with testing-driven tier assignments.
 *  All phones start at phone-low. Promote only after confirmed testing.
 *  iPads start at tablet (tested stable). */
const DEVICE_REGISTRY: DeviceRegistryEntry[] = [
  // ── iPads (tested stable at tablet tier) ──────────────────────
  { w: 810, h: 1080, dpr: 2, label: 'iPad 10th Gen', currentTier: 'tablet', overrides: {} },
  { w: 820, h: 1180, dpr: 2, label: 'iPad Air 4/5', currentTier: 'tablet', overrides: {},
    testStatus: 'tested-2026-02-25: 30fps tablet, stable' },
  { w: 834, h: 1194, dpr: 2, label: 'iPad Pro 11"', currentTier: 'tablet', overrides: {} },
  { w: 1024, h: 1366, dpr: 2, label: 'iPad Pro 12.9"', currentTier: 'tablet', overrides: {} },
  { w: 768, h: 1024, dpr: 2, label: 'iPad 9th Gen / Mini', currentTier: 'tablet', overrides: {} },

  // ── iPhones — TESTED devices (promoted from phone-low) ───────

  // 360×780 @3x — 13 Mini/12 Mini (A14, 4GB) — TESTED: 35 FPS phone-high, stable
  { w: 360, h: 780, dpr: 3, label: 'iPhone 13 Mini/12 Mini', currentTier: 'phone-high',
    overrides: { musicUIScale: 1.5 },
    testStatus: 'tested-2026-02-25: 35fps phone-high, stable' },

  // ── iPhones — PROMOTED based on 12 Mini test data + chip analysis ──

  // 393×852 @3x — 16/15/15 Pro/14 Pro (weakest: A16 6GB)
  // MacClaude sim 14 Pro: 45-53 FPS at 628 MB (old). All devices A16+ 6GB+.
  // Promoted to phone-high with quality overrides: more cars, better reflections.
  { w: 393, h: 852, dpr: 3, label: 'iPhone 16/15/15P/14P', currentTier: 'phone-high',
    overrides: { carCount: 3, reflectionSkip: 1, renderScale: 0.85 },
    testStatus: 'sim-2026-02-26: 14P 45-53fps@628MB. A16+ 6GB+, overrides above phone-high base' },

  // 390×844 @3x — 16e/14/13/13 Pro/12/12 Pro (weakest: A14 4GB)
  // MacClaude sim 13 Pro: 47-48 FPS start, 37-47 FPS gameplay@628 MB.
  // Weakest A14 4GB = same chip as tested 12 Mini (35 FPS phone-high, stable).
  { w: 390, h: 844, dpr: 3, label: 'iPhone 16e/14/13/13P/12/12P', currentTier: 'phone-high',
    overrides: {},
    testStatus: 'sim-2026-02-26: 13P 37-47fps@628MB. Weakest A14 4GB = same as tested 12 Mini' },

  // ── iPhones — UNTESTED (start at phone-low, promote after testing) ──

  // 440×956 @3x — iPhone 16 Pro Max (A18 Pro, 8GB)
  { w: 440, h: 956, dpr: 3, label: 'iPhone 16 Pro Max', currentTier: 'phone-low', overrides: {} },
  // 402×874 @3x — iPhone 16 Pro (A18 Pro, 8GB)
  { w: 402, h: 874, dpr: 3, label: 'iPhone 16 Pro', currentTier: 'phone-low', overrides: {} },
  // 430×932 @3x — 16+/15+/15 Pro Max/14 Pro Max (weakest: A15 6GB)
  { w: 430, h: 932, dpr: 3, label: 'iPhone 16+/15+/15PM/14PM', currentTier: 'phone-low', overrides: {} },
  // 428×926 @3x — 14+/13 Pro Max/12 Pro Max (weakest: A14 6GB)
  { w: 428, h: 926, dpr: 3, label: 'iPhone 14+/13PM/12PM', currentTier: 'phone-low', overrides: {} },

  // ── iPhones — phone-low (tested or old hardware, stays here) ──

  // 375×812 @3x — X/XS/11 Pro (A11-A13, 3-4GB) — OOM at desktop, stable at phone-low
  { w: 375, h: 812, dpr: 3, label: 'iPhone X/XS/11 Pro', currentTier: 'phone-low', overrides: {},
    testStatus: 'tested-2026-02-25: OOM at desktop, stable phone-low' },
  // 414×896 @3x — XS Max/11 Pro Max (A12/A13, 4GB)
  { w: 414, h: 896, dpr: 3, label: 'iPhone XS Max/11 Pro Max', currentTier: 'phone-low', overrides: {} },
  // 414×896 @2x — XR/11 (A12/A13, LCD @2x)
  { w: 414, h: 896, dpr: 2, label: 'iPhone XR/11', currentTier: 'phone-low', overrides: {} },
  // 375×667 @2x — 8/SE 2/SE 3 (A11-A15, LCD @2x, 2-4GB)
  { w: 375, h: 667, dpr: 2, label: 'iPhone SE 2/SE 3/8', currentTier: 'phone-low', overrides: {} },
  // 414×736 @3x — 8 Plus (A11, 3GB)
  { w: 414, h: 736, dpr: 3, label: 'iPhone 8 Plus', currentTier: 'phone-low', overrides: {} },
  // 320×568 @2x — SE 1st Gen (A9, 2GB)
  { w: 320, h: 568, dpr: 2, label: 'iPhone SE 1st Gen', currentTier: 'phone-low', overrides: {} },
];

/** Detect device and return the appropriate profile.
 *  Priority: ?profile= URL param > fingerprint match > heuristic fallback.
 *  Unknown phones default to phone-low (safest). Promote after testing. */
const VALID_SPRITE_TIERS: SpriteTier[] = ['s100', 's75', 's50', 's37', 's25'];

export function detectDeviceProfile(): DeviceProfile {
  const params = new URLSearchParams(location.search);
  let profile: DeviceProfile;

  // 1. Manual override via URL param: ?profile=desktop|tablet|phone-high|gen-mobile|phone-low
  const override = params.get('profile') as DeviceTier | null;
  if (override && TIER_DEFAULTS[override]) {
    profile = { ...TIER_DEFAULTS[override] };
    profile.label = `${profile.label} (override)`;
  }
  // 2. Try fingerprint match (iOS devices) — uses DEVICE_REGISTRY + buildProfile
  else if (isiOS()) {
    const w = Math.min(screen.width, screen.height);  // portrait width
    const h = Math.max(screen.width, screen.height);  // portrait height
    const dpr = window.devicePixelRatio;

    let matched = false;
    for (const entry of DEVICE_REGISTRY) {
      if (entry.w === w && entry.h === h && Math.abs(entry.dpr - dpr) < 0.5) {
        profile = buildProfile(entry);
        matched = true;
        break;
      }
    }

    if (!matched) {
      // 3. iOS but no fingerprint match — guess by screen size
      if (w >= 700) {
        profile = { ...TIER_DEFAULTS['tablet'] };
        profile.label = `Unknown iPad (${w}×${h} @${dpr}x)`;
      } else {
        profile = { ...TIER_DEFAULTS['phone-low'] };
        profile.label = `Unknown iPhone (${w}×${h} @${dpr}x)`;
        profile.musicUIScale = autoMusicUIScale();
      }
    }
  }
  // 4. Non-iOS mobile — phone-low fallback (unknown = start at bottom)
  else if (detectMobileLike()) {
    const w = Math.min(screen.width, screen.height);
    if (w >= 700) {
      profile = { ...TIER_DEFAULTS['tablet'] };
      profile.label = `Android Tablet (${w}×${screen.height})`;
    } else {
      profile = { ...TIER_DEFAULTS['phone-low'] };
      profile.label = `Android Phone (${w}×${screen.height})`;
      profile.musicUIScale = autoMusicUIScale();
    }
  }
  // 5. Desktop
  else {
    profile = { ...TIER_DEFAULTS['desktop'] };
  }

  // Apply ?sprite= override — works for ALL detection paths
  const spriteOverride = params.get('sprite') as SpriteTier | null;
  if (spriteOverride && VALID_SPRITE_TIERS.includes(spriteOverride)) {
    profile!.spriteTier = spriteOverride;
  }

  return profile!;
}
