// src/config/phoneManifest.ts — AUTO-GENERATED by gen-phone-assets.py
// DO NOT EDIT MANUALLY. Re-run: python scripts/gen-phone-assets.py

export interface PhoneAssetEntry {
  file: string;
  fw?: number;  // frame width (spritesheets)
  fh?: number;  // frame height (spritesheets)
  w?: number;   // image width (backgrounds)
  h?: number;   // image height (backgrounds)
  lanes?: { file: string; fw: number; fh: number }[];  // per-lane mode only
}

export const PHONE_MANIFEST: Record<string, PhoneAssetEntry> = {
  'player-ride': { file: 'assets/phone/player-ride-phone.png', fw: 101, fh: 85 },
  'player-attack': { file: 'assets/phone/player-attack-phone.png', fw: 118, fh: 85 },
  'player-start': { file: 'assets/phone/player-start-phone.png', fw: 103, fh: 89 },
  'player-powered': { file: 'assets/phone/player-powered-phone.png', fw: 131, fh: 85 },
  'player-speedup': { file: 'assets/phone/player-speedup-phone.png', fw: 128, fh: 91 },
  'player-rocket-launch': { file: 'assets/phone/player-rocket-launch-phone.png', fw: 157, fh: 96 },
  'player-collect-rocket': { file: 'assets/phone/player-collect-rocket-phone.png', fw: 142, fh: 107 },
  'player-collect-shield': { file: 'assets/phone/player-collect-shield-phone.png', fw: 142, fh: 107 },
  'player-collect-hit': { file: 'assets/phone/player-collect-hit-phone.png', fw: 142, fh: 107 },
  'car-001': { file: 'assets/phone/car-001-phone.png', fw: 224, fh: 94 },
  'car-002': { file: 'assets/phone/car-002-phone.png', fw: 224, fh: 94 },
  'car-003': { file: 'assets/phone/car-003-phone.png', fw: 224, fh: 94 },
  'car-004': { file: 'assets/phone/car-004-phone.png', fw: 224, fh: 94 },
  'car-005': { file: 'assets/phone/car-005-phone.png', fw: 224, fh: 94 },
  'car-006': { file: 'assets/phone/car-006-phone.png', fw: 224, fh: 94 },
  'car-007': { file: 'assets/phone/car-007-phone.png', fw: 224, fh: 94 },
  'car-008': { file: 'assets/phone/car-008-phone.png', fw: 224, fh: 94 },
  'car-009': { file: 'assets/phone/car-009-phone.png', fw: 224, fh: 94 },
  'car-010': { file: 'assets/phone/car-010-phone.png', fw: 224, fh: 94 },
  'car-011': { file: 'assets/phone/car-011-phone.png', fw: 224, fh: 94 },
  'car-012': { file: 'assets/phone/car-012-phone.png', fw: 224, fh: 94 },
  'car-013': { file: 'assets/phone/car-013-phone.png', fw: 224, fh: 94 },
  'car-014': { file: 'assets/phone/car-014-phone.png', fw: 224, fh: 94 },
  'car-015': { file: 'assets/phone/car-015-phone.png', fw: 224, fh: 94 },
  'car-016': { file: 'assets/phone/car-016-phone.png', fw: 224, fh: 94 },
  'car-017': { file: 'assets/phone/car-017-phone.png', fw: 224, fh: 94 },
  'car-018': { file: 'assets/phone/car-018-phone.png', fw: 224, fh: 94 },
  'car-019': { file: 'assets/phone/car-019-phone.png', fw: 224, fh: 94 },
  'car-020': { file: 'assets/phone/car-020-phone.png', fw: 224, fh: 94 },
  'barrier': { file: 'assets/phone/barrier-phone.png', fw: 32, fh: 67 },
  'barrier-reflection': { file: 'assets/phone/barrier-reflection-phone.png', fw: 32, fh: 67 },
  'pickup-rocket': { file: 'assets/phone/pickup-rocket-phone.png', fw: 69, fh: 69 },
  'pickup-shield': { file: 'assets/phone/pickup-shield-phone.png', fw: 69, fh: 69 },
  'rocket-proj': { file: 'assets/phone/rocket-proj-phone.png', fw: 71, fh: 37 },
  'slash-vfx': { file: 'assets/phone/slash-vfx-phone.png', fw: 140, fh: 120 },
  'explosion': { file: 'assets/phone/explosion-phone.png', fw: 279, fh: 279 },
  'sky': { file: 'assets/phone/sky-phone.jpg', w: 1440, h: 308 },
  'buildings-back': { file: 'assets/phone/buildings-back-phone.png', w: 1440, h: 123 },
  'buildings-front': { file: 'assets/phone/buildings-front-phone.png', w: 1440, h: 122 },
  'road-tile': { file: 'assets/phone/road-tile-phone.jpg', w: 1440, h: 2253 },
  'road-lines': { file: 'assets/phone/road-lines-phone.png', w: 1440, h: 2253 },
  'railing': { file: 'assets/phone/railing-phone.jpg', w: 1440, h: 633 },
  'puddle': { file: 'assets/phone/puddle-phone.png', w: 274, h: 81 },
};
