#!/bin/bash
DEST="C:/Users/mikey/Claude_Playground/dp_moto/public/assets/audio/music/Rythem_Songs"
SRC="D:/hume music/Music"
mkdir -p "$DEST"

copied=0
missing=0
missing_list=""

copy_track() {
  local src="$1"
  local dest_name="$2"
  if [ -f "$src" ]; then
    cp "$src" "$DEST/$dest_name"
    echo "  OK: $dest_name"
    copied=$((copied + 1))
  else
    echo "  MISS: $dest_name"
    missing=$((missing + 1))
    missing_list="$missing_list  - $dest_name
"
  fi
}

echo "=== DEATHPIXIE ==="
copy_track "$SRC/deathpixie music/Ate/Master/ate 1.5 [SPOTIFY MASTER 16bit 44.1khz].mp3" "DEATHPIXIE - ATE.mp3"
copy_track "$SRC/deathpixie music/Blood Beat/Master/blood beat 1.0.5.3.wav" "DEATHPIXIE - BLOOD BEAT.wav"
copy_track "$SRC/deathpixie music/Death Machine/Master/death machine 1.8 [SPOTIFY MASTER 16bit 44.1khz].mp3" "DEATHPIXIE - DEATH MACHINE.mp3"
copy_track "$SRC/deathpixie music/dominatrix/Master/dominatrix 1.5 [MAIN MASTERED 16bit 44.1khz].wav" "DEATHPIXIE - DOMINATRIX.wav"
copy_track "$SRC/deathpixie music/Gas on Fire/Master/gas on fire 1.5 [SPOTIFY MASTER 16bit 44.1khz].wav" "DEATHPIXIE - GAS ON FIRE.wav"
copy_track "$SRC/deathpixie music/hell girl/Master/hell girl 6.1.4 FINAL MASTER FOR SPOTIFY.wav" "DEATHPIXIE - HELL GIRL.wav"
copy_track "$SRC/deathpixie music/Hentai/Master/hentai 1.6.mp3" "DEATHPIXIE - HENTAI.mp3"
copy_track "$SRC/deathpixie music/Kawasaki/Master/kawasaki 3.7 master for spotify 2448.wav" "DEATHPIXIE - KAWASAKI.wav"
copy_track "$SRC/deathpixie music/Killamonsta/Master/killamonsta 5.5 krupa.wav" "DEATHPIXIE - KILLAMONSTA.wav"
copy_track "$SRC/deathpixie music/lil b_tch/Master/Death Pixie - Lil Bitch 4.9 [MAIN MASTERED 24bit 48khz] [FINAL].mp3" "DEATHPIXIE - LIL BITCH.mp3"
copy_track "$SRC/deathpixie music/Main Character Energy/Master/main character energy 1.5.mp3" "DEATHPIXIE - MAIN CHARACTER ENERGY.mp3"
copy_track "$SRC/deathpixie music/More Cowbell/Master/more cowbell 1.9 [SPOTIFY MASTER 16bit 44.1khz].mp3" "DEATHPIXIE - MORE COWBELL.mp3"
copy_track "$SRC/deathpixie music/Nosferatu/Master/nosferatu 1.4.wav" "DEATHPIXIE - NOSFERATU.wav"
copy_track "$SRC/deathpixie music/okinawa/MASTER/okinawa 6.2 (1).wav" "DEATHPIXIE - OKINAWA.wav"
copy_track "$SRC/deathpixie music/RED MALIBU/Master/red malibu 1.5.wav" "DEATHPIXIE - RED MALIBU.wav"
copy_track "$SRC/deathpixie music/Safe Word/Master/safe word 4.0 [MAIN MASTERED 24bit 48khz] [FINAL].wav" "DEATHPIXIE - SAFE WORD.wav"
copy_track "$SRC/deathpixie music/Slip/Master/slip 3.4.mp3" "DEATHPIXIE - SLIP.mp3"
copy_track "$SRC/deathpixie music/Tokyo Blood/Master/tokyo blood 5.1 [SPOTIFY MASTER 16bit 44.1khz].mp3" "DEATHPIXIE - TOKYO BLOOD.mp3"
copy_track "$SRC/deathpixie music/Walking Nightmare/Master/walking nightmare 3.2 [MAIN MASTERED] 24bit 48khz.wav" "DEATHPIXIE - WALKING NIGHTMARE.wav"
copy_track "$SRC/deathpixie music/MERRY DEATHMAS/MASTER/merry deathmas 1.6.wav" "DEATHPIXIE - MERRY DEATHMAS.wav"

# Asylum EP tracks
copy_track "$SRC/deathpixie music/Asylum EP/ASYLUM EP - MASTERS/04 44 (1).wav" "DEATHPIXIE - 44.wav"
copy_track "$SRC/deathpixie music/Asylum EP/ASYLUM EP - MASTERS/03 DEATHPIXIE_S PROLOGUE (1).wav" "DEATHPIXIE - DEATHPIXIES PROLOGUE.wav"
copy_track "$SRC/deathpixie music/Asylum EP/ASYLUM EP - MASTERS/02 MONSTER IN MY BED (1).wav" "DEATHPIXIE - MONSTER IN MY BED.wav"

# Matar
copy_track "$SRC/deathpixie music/Matar #9 KTB/Master/matar  9 ktb 1.2 [SPOTIFY MASTER 16bit 44.1khz].mp3" "DEATHPIXIE - MATAR 9 KTB.mp3"

echo ""
echo "=== DEATHPIXIE COLLABS ==="
copy_track "$SRC/deathpixie music/NIGHTMARECORE - DP x Cypariss/Master/nightmarecore 1.0.mp3" "DEATHPIXIE x CYPARISS - NIGHTMARECORE.mp3"
copy_track "$SRC/deathpixie music/FEED MY APPETITE w- CISZAK/Master/FEED MY APPETITE (2.6) [FINAL SPOTIFY MASTER].wav" "DEATHPIXIE x CISZAK - FEED MY APPETITE.wav"
copy_track "$SRC/deathpixie music/Raise Your Weapon/Master + Extended/Ryp Mix_Mast.wav" "DEATHPIXIE x DEADMAU5 - RAISE YOUR WEAPON.wav"
copy_track "$SRC/deathpixie music/Safe Word (Deathmix with Lexy Panterra)/Master/safe word 4.0.6 lex feat [MASTER FOR SPOTIFY 16bit 44.1khz].wav" "DEATHPIXIE x LEXY PANTERRA - SAFE WORD DEATHMIX.wav"
copy_track "$SRC/deathpixie music/Die & Live Again Feat. Meryll/Master/die and live again 3.2.wav" "DEATHPIXIE x MERYLL - DIE AND LIVE AGAIN.wav"
copy_track "$SRC/deathpixie music/Hell Girl  II - Oddkidout Remix/Master/HELLGIRL OKO REMIX v3.mp3" "DEATHPIXIE x ODDKIDOUT - HELL GIRL II.mp3"
copy_track "$SRC/deathpixie music/Grim Reaper - DP x Pro6lema/Master/grim reaper 3.2.mp3" "DEATHPIXIE x PRO6LEMA - GRIM REAPER.mp3"
copy_track "$SRC/deathpixie music/BRAIN ROT/Master/BRAIN ROT 1.3.mp3" "DEATHPIXIE x REZADEAD - BRAIN ROT.mp3"
copy_track "$SRC/deathpixie music/Digital Kill Shit w- Rezadead/Master/digital kill sh!t 1.2.mp3" "DEATHPIXIE x REZADEAD - DIGITAL KILL SHIT.mp3"
copy_track "$SRC/deathpixie music/Asylum EP/ASYLUM EP - MASTERS/01 LET YOU LIE (FEAT. SKYLAR GREY) (1).wav" "DEATHPIXIE x SKYLAR GREY - LET YOU LIE.wav"
copy_track "$SRC/deathpixie music/New Blood Feat. Raizhell/Master/NEW BLOOD.wav" "DEATHPIXIE x RAIZHELL - NEW BLOOD.wav"
copy_track "$SRC/deathpixie music/Welcome to the freakshow w- T78/Master + Extended/Welcome to the freak show (Spotify MASTER).mp3" "DEATHPIXIE x T78 - WELCOME TO THE FREAKSHOW.mp3"
copy_track "$SRC/deathpixie music/PHONK TECHNO W- WHIPPED CREAM/Master/phonk techno 2.3.wav" "DEATHPIXIE x WHIPPED CREAM - PHONK TECHNO.wav"
copy_track "$SRC/deathpixie music/Blind feat. Isolate.exe/Masters/Blind.mp3" "ISOLATE.EXE x DEATHPIXIE - BLIND.mp3"

echo ""
echo "=== ANGELBABY ==="
copy_track "$SRC/angelbaby music/am i just high_/Master/am i just high_ v8.0 72BPM.wav" "ANGELBABY - AM I JUST HIGH.wav"
copy_track "$SRC/angelbaby music/coca cola/Master/coca cola 1.7.wav" "ANGELBABY - COCA COLA.wav"
copy_track "$SRC/angelbaby music/die4you/Master/die4you_1.8.wav" "ANGELBABY - DIE4YOU.wav"
copy_track "$SRC/angelbaby music/Endless Summer/Master/endless summer 1.5 MASTER .mp3" "ANGELBABY - ENDLESS SUMMER.mp3"
copy_track "$SRC/angelbaby music/Feel Good Inc/Master/feel good inc cover 3.4 [MAIN MASTERED] 24bit 48khz (1).wav" "ANGELBABY - FEEL GOOD INC.wav"
copy_track "$SRC/angelbaby music/Grinch on Christmas/Master/grinch on christmas 2.3 [SPOTIFY MASTER 24bit 44.1khz] (1).wav" "ANGELBABY - GRINCH ON CHRISTMAS.wav"
copy_track "$SRC/angelbaby music/I Broke Time/Master/I BROKE TIME MASTER.wav" "ANGELBABY - I BROKE TIME.wav"
copy_track "$SRC/angelbaby music/New Location/Master/new location 2.5.wav" "ANGELBABY - NEW LOCATION.wav"
copy_track "$SRC/angelbaby music/Nothing Really Matters/Master/NOTHING REALLY MATTERS (CATON MASTER1) V1 91BPM 2.3.25 (1).wav" "ANGELBABY - NOTHING REALLY MATTERS.wav"
copy_track "$SRC/angelbaby music/surrender/Master/surrender 1.2.wav" "ANGELBABY - SURRENDER.wav"
copy_track "$SRC/angelbaby music/Unseen/Main Master/Unseen - Yianni Mix v03 - MAIN (Mastered) - mstr rev1 - 11 7 23 (1).wav" "ANGELBABY - UNSEEN.wav"
copy_track "$SRC/angelbaby music/Walking Dead/Master/Walking Dead v7.0 107BPM 6.8.24 [MAIN MASTERED 16bit 44.1khz].wav" "ANGELBABY - WALKING DEAD.wav"
copy_track "$SRC/angelbaby music/Wayside/Master/way side 2.2.wav" "ANGELBABY - WAYSIDE.wav"
copy_track "$SRC/angelbaby music/What happens when we die/Master/what happens when we die 3.0.wav" "ANGELBABY - WHAT HAPPENS WHEN WE DIE.wav"

echo ""
echo "=== ANGELBABY COLLABS ==="
copy_track "$SRC/angelbaby music/facedown with Arrested Youth/Master/FACEDOWN 1.7.wav" "ANGELBABY x ARRESTED YOUTH - FACEDOWN.wav"
copy_track "$SRC/angelbaby music/Live Forever/Master/live forever - 2.1 feat v3.3 option 2 - MAIN (Mastered) - 8 3 23.wav" "ANGELBABY x BLVCK SVM - LIVE FOREVER.wav"
copy_track "$SRC/angelbaby music/Minted/Master/minted 2.0 - MAIN (Mastered) - 7 5 22 (1).wav" "ANGELBABY x BRANDYN BURNETTE - MINTED.wav"
copy_track "$SRC/angelbaby music/God Made me Like This/Master/God Made Me Like This 92BPM (CatonMaster1).mp3" "ANGELBABY x BRYCE VINE - GOD MADE ME LIKE THIS.mp3"
copy_track "$SRC/angelbaby music/The Otherside/Master/MP3 Versions/Otherside v5.0 146BPM - MAIN (Mastered) - 5 20 22.mp3" "ANGELBABY x GINO THE GHOST - THE OTHERSIDE.mp3"
copy_track "$SRC/angelbaby music/I_m Fine _(_/Master/I_m Fine - Yianni Mix v24 (Angel Intro) - MAIN (Mastered) - de-esser edit 2 - 48kHz 24bit Apple Digital Master - 2 23 24.wav" "ANGELBABY x GRIMESAI - IM FINE.wav"
copy_track "$SRC/angelbaby music/Life is Good/Master/Master/24b-A_Life Is Good (JELLIS MIX 444Hz)_BECKER MASTER (1).wav" "ANGELBABY x JAGWAR TWIN - LIFE IS GOOD.wav"
copy_track "$SRC/angelbaby music/wake up fucked up/Master/wake up fucked up 1.7.wav" "ANGELBABY x JFARRARI - WAKE UP FUCKED UP.wav"
copy_track "$SRC/angelbaby music/Cut The Lights Feat. Madalen Duke/Master/cut the lights 2.5.mp3" "ANGELBABY x MADALEN DUKE - CUT THE LIGHTS.mp3"
copy_track "$SRC/angelbaby music/so dumb w- Porchlight/Master/so dumb 2.2.wav" "ANGELBABY x PORCHLIGHT - SO DUMB.wav"
copy_track "$SRC/angelbaby music/Before You/Masters/Hume - Before You - CH MIX R11 rap vocal edit rev - MAIN (Mastered) - 5 9 23.wav" "ANGELBABY x PRETTYMUCH - BEFORE YOU.wav"
copy_track "$SRC/angelbaby music/before you (Night Tales Remix)/Master/Before You (Night Tales Remix).wav" "ANGELBABY x PRETTYMUCH x NIGHT TALES - BEFORE YOU REMIX.wav"
copy_track "$SRC/angelbaby music/before you (Oliver Nelson Remix)/Master/Before You (Oliver Nelson Remix) v2.wav" "ANGELBABY x PRETTYMUCH x OLIVER NELSON - BEFORE YOU REMIX.wav"
copy_track "$SRC/angelbaby music/Dark Mode Feat. Rudywade/Master/dark mode 2.5.mp3" "ANGELBABY x RUDYWADE - DARK MODE.mp3"
copy_track "$SRC/angelbaby music/View From The Moon/Master/Moon - mix 2.3 - MAIN mv2 (Mastered) - 6 13 22.wav" "ANGELBABY x STOLAR - VIEW FROM THE MOON.wav"
copy_track "$SRC/angelbaby music/Black Hole/Master/Black Hole - Yianni Mix v04 - MAIN (Mastered) - 6 29 23.wav" "ANGELBABY x TK - BLACK HOLE.wav"
copy_track "$SRC/angelbaby music/Imposter/Master/Imposter v11 85BPM 2.24.25.wav" "ANGELBABY x VOILA - IMPOSTER.wav"

echo ""
echo "=== KAI.WAV ==="
copy_track "$SRC/kai.wav music/Better when its you/Master/better when its u 1.2 [SPOTIFY MASTER].wav" "KAI.WAV - BETTER WHEN ITS YOU.wav"
copy_track "$SRC/kai.wav music/Funktion/Master/funktion 2.8 [SPOTIFY MASTER 16bit 44.1khz].mp3" "KAI.WAV - FUNKTION.mp3"
copy_track "$SRC/kai.wav music/Love in the Music/Master + Extended Version/kai.wav - Love in The Music  Radio Edit 16_44.1 Master.wav" "KAI.WAV - LOVE IN THE MUSIC.wav"
copy_track "$SRC/kai.wav music/Set me free/Master/set me free 1.4 (1).wav" "KAI.WAV - SET ME FREE.wav"
copy_track "$SRC/kai.wav music/That_s a vibe/Master/thats a vibe 1.4.1.mp3" "KAI.WAV - THATS A VIBE.mp3"
copy_track "$SRC/kai.wav music/Top Floor/Master/top floor 1.4 [SPOTIFY MASTER].wav" "KAI.WAV - TOP FLOOR.wav"
copy_track "$SRC/kai.wav music/uno dos tres/Master/Uno, Dos, Tres 1.5.wav" "KAI.WAV - UNO DOS TRES.wav"
copy_track "$SRC/kai.wav music/I need a dollar (kai.wav x Aloe Blacc)/Master + Extended mix/Aloe Blacc & Kai.wav - I Need A Dollar (Radio Edit) (Maitland Mix) v7.wav" "KAI.WAV x ALOE BLACC - I NEED A DOLLAR.wav"
copy_track "$SRC/kai.wav music/I need a Dollar (Tiago Ribeiro Remix)/Master/01 kai.wav & Aloe Blacc - I Need A Dollar (Tiago Ribeiro Remix) NEW - AUCN32400273.wav" "KAI.WAV x ALOE BLACC x TIAGO RIBEIRO - I NEED A DOLLAR REMIX.wav"

echo ""
echo "=== LOFI GMA ==="
copy_track "$SRC/Lofi gma music/bonsai/Master/Bonsai (1).mp3" "LOFI GMA - BONSAI.mp3"
copy_track "$SRC/Lofi gma music/cherry tree/Master/Cherry Tree (1).mp3" "LOFI GMA - CHERRY TREE.mp3"
copy_track "$SRC/Lofi gma music/Garden dreams/Master/garden dreams.mp3" "LOFI GMA - GARDEN DREAMS.mp3"
copy_track "$SRC/Lofi gma music/gentle night/Master/gentle night.mp3" "LOFI GMA - GENTLE NIGHT.mp3"
copy_track "$SRC/Lofi gma music/green tea/Master/Green tea.wav" "LOFI GMA - GREEN TEA.wav"
copy_track "$SRC/Lofi gma music/quiet hour/Master/Quiet hour (1).mp3" "LOFI GMA - QUIET HOUR.mp3"
copy_track "$SRC/Lofi gma music/Rainy window/Master/rainy window.mp3" "LOFI GMA - RAINY WINDOW.mp3"
copy_track "$SRC/Lofi gma music/ramen/Ramen - Release Assets/master/Tonkotsu Ramen Mastered 2.mp3" "LOFI GMA - RAMEN.mp3"
copy_track "$SRC/Lofi gma music/shumai/Master/Shumai Mastered.mp3" "LOFI GMA - SHUMAI.mp3"
copy_track "$SRC/Lofi gma music/soup dumplings/Master/soup dumplings 1.0.mp3" "LOFI GMA - SOUP DUMPLINGS.mp3"
copy_track "$SRC/Lofi gma music/tea leaves/Master/tea leaves.mp3" "LOFI GMA - TEA LEAVES.mp3"

echo ""
echo "=== PRO6LEMA ==="
copy_track "$SRC/Pro6lema music/Bicuda Phonk/Master/bicuda phonk.mp3" "PRO6LEMA - BICUDA PHONK.mp3"
copy_track "$SRC/Pro6lema music/Breja Breja/Master/Pro6lema - Breja Breja .wav" "PRO6LEMA - BREJA BREJA.wav"
copy_track "$SRC/Pro6lema music/Cortura/Master/Cortura 1.1.mp3" "PRO6LEMA - CORTURA.mp3"
copy_track "$SRC/Pro6lema music/FEITIÇO_99/Master/FEITIÇO_99 1.1.mp3" "PRO6LEMA - FEITICO 99.mp3"
copy_track "$SRC/Pro6lema music/Hipnotica/Master/Hipnotica.mp3" "PRO6LEMA - HIPNOTICA.mp3"
copy_track "$SRC/Pro6lema music/Hoje em dia é dificil encontrar/Master/hoje em dia é dificil encontrar 1.5 [SPOTIFY MASTER 16bit 44.1khz].mp3" "PRO6LEMA - HOJE EM DIA E DIFICIL ENCONTRAR.mp3"
copy_track "$SRC/Pro6lema music/Italy/Master/italy 1.3.mp3" "PRO6LEMA - ITALY.mp3"
copy_track "$SRC/Pro6lema music/Minion Brain Rot/Master/minion brain rot 1.4.wav" "PRO6LEMA - MINION BRAIN ROT.wav"
copy_track "$SRC/Pro6lema music/Que Perigx/Master/QUE PERIGX.mp3" "PRO6LEMA - QUE PERIGX.mp3"
copy_track "$SRC/Pro6lema music/Que Yona/Master/que yona 1.1.mp3" "PRO6LEMA - QUE YONA.mp3"
copy_track "$SRC/Pro6lema music/Trancemelodia/Master/TRANCEMELODIA.mp3" "PRO6LEMA - TRANCEMELODIA.mp3"
copy_track "$SRC/Pro6lema music/Vida/Master/vida 1.1.mp3" "PRO6LEMA - VIDA.mp3"

echo ""
echo "=== PRO6LEMA COLLABS ==="
copy_track "$SRC/Pro6lema music/Genesis feat. Chilx and Rubikdice/Master/GENESIS.mp3" "PRO6LEMA x CHILX x RUBIKDICE - GENESIS.mp3"
copy_track "$SRC/Pro6lema music/Menina (Pro6blema x Deathpixie)/Master/menina de vermelho 2.0.wav" "PRO6LEMA x DEATHPIXIE - MENINA.wav"
copy_track "$SRC/Pro6lema music/All Eyes on Rani - Pro6lema x HXDES/Master/Rani (With vocal chops ).mp3" "PRO6LEMA x HXDES - ALL EYES ON RANI.mp3"
copy_track "$SRC/Pro6lema music/Vapo No Setor/Master/vapo no setor 1.3.mp3" "PRO6LEMA x NASHI x ANKXRA - VAPO NO SETOR.mp3"

echo ""
echo "=== TWENTY16 ==="
copy_track "$SRC/twenty16 music/Stranger/Master/stranger master v2 [SPOTIFY MASTER 16bit 44.1khz].wav" "TWENTY16 - STRANGER.wav"

echo ""
echo "=========================================="
echo "COPIED: $copied tracks"
echo "MISSING: $missing tracks"
if [ $missing -gt 0 ]; then
  echo "Missing tracks:"
  echo "$missing_list"
fi
echo "=========================================="
